# Generated by Django 5.1.5 on 2025-01-31 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_is_patient_customuser_verification_expiry_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DoctorProfile',
        ),
    ]
